fix: update Dockerfiles to include apache rewrite module and build php zts

diff --git a/php/apache/Dockerfile b/php/apache/Dockerfile
--- a/php/apache/Dockerfile
+++ b/php/apache/Dockerfile
@@ -20,7 +20,6 @@ ENV LOG_FILE="/tmp/build-log.md"
 # Create build log
 RUN touch ${LOG_FILE}
 
-
 # Base user setup (critique)
 ENV STEP="User setup"
 RUN (apt-get update && export DEBIAN_FRONTEND=noninteractive \
@@ -32,6 +31,7 @@ RUN (apt-get update && export DEBIAN_FRONTEND=noninteractive \
     && usermod -aG www-data ${USERNAME} \
     && apt-get clean -y && rm -rf /var/lib/apt/lists/* \
     && echo "$SUCCESS $STEP" >> $LOG_FILE) || echo "$FAILURE $STEP" >> $LOG_FILE
+
 # PHP configuration
 ENV STEP="PHP configuration"
 RUN (echo "display_startup_errors = Off" > /usr/local/etc/php/php.ini \
@@ -74,6 +74,11 @@ ENV STEP="Composer"
 RUN (curl -sSL https://getcomposer.org/installer | php \
     && chmod +x composer.phar \
     && mv composer.phar /usr/local/bin/composer \
+    && echo "$SUCCESS $STEP" >> $LOG_FILE) || echo "$FAILURE $STEP" >> $LOG_FILE
+
+# Enable rewrite module
+ENV STEP="Apache rewrite module"
+RUN (a2enmod rewrite \
     && echo "$SUCCESS $STEP" >> $LOG_FILE) || echo "$FAILURE $STEP" >> $LOG_FILE
 
 USER $USERNAME
